blueprint:
  name: Zigbee2MQTT_Xiaomi큐브
  description: ""
  source_url: https://github.com/so2chi/hablueprint/blob/main/Zigbee2MQTT_Xiaomi_Cube.yaml
  domain: automation
  homeassistant:
    min_version: 2023.3.0
  input:    
    topic:
      name: Topic
      description: '미큐브 액션 MQTT zigbee2mqtt/기기/action'
      default: zigbee2mqtt/?
      selector:
        text:
          multiline: false
    shake:
      name: "흔들기"
      description: ''
      default: []
      selector:
        action: {}
    fall:
      name: "하강"
      description: '공중에서 아래로'
      default: []
      selector:
        action: {}
    slide_any:
      name: "슬라이드"
      description: "아무쪽이나 밀기"
      default: []
      selector:
        action: {}
    doubletap_any:
      name: "두번 탭"
      description: ""
      default: []
      selector:
        action: {}
    flipped90_any:
      name: "90도 회전"
      description: ""
      default: []
      selector:
        action: {}
    flipped180_any:
      name: "180도 회전"
      description: ""
      default: []
      selector:
        action: {}
    rotate_cw_any:
      name: "우측 회전"
      description: ""
      default: []
      selector:
        action: {}
    rotate_ccw_any:
      name: "좌측 회전"
      description: ""
      default: []
      selector:
        action: {}    
mode: single
max_exceeded: silent
trigger:
- platform: mqtt
  topic: !input topic
condition:
- condition: template
  value_template: '{{ trigger.payload is defined and trigger.payload in (''rotate_right'', ''rotate_left'',
    ''flip90'', ''flip180'', ''slide'', ''tap'', ''shake'', ''fall'', ''throw'', ''wakeup'') }}'
action:
- variables:
    command: '{{ trigger.payload }}'
- alias: "모든케이스"
  choose:
  - conditions: '{{ command == "slide" }}'
    sequence: !input slide_any
  - conditions: '{{ command == "tap" }}'
    sequence: !input doubletap_any
  - conditions: '{{ command == "flip90" }}'
    sequence: !input flipped90_any
  - conditions: '{{ command == "flip180" }}'
    sequence: !input flipped180_any
  - conditions: '{{ command == "rotate_right" }}'
    sequence: !input rotate_cw_any
  - conditions: '{{ command == "rotate_left" }}'
    sequence: !input rotate_ccw_any
  - conditions: '{{ command == "shake" }}'
    sequence: !input shake
  - conditions: '{{ command == "fall" }}'
    sequence: !input fall
- alias: 딜레이
  delay: 00:00:01
